CREATE TABLE tb_client (
                           id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name        VARCHAR(255) NOT NULL,
                           email       VARCHAR(255) NOT NULL,
                           cpf_or_cnpj VARCHAR(255) NOT NULL,
                           CONSTRAINT uk_client_email UNIQUE (email),
                           CONSTRAINT uk_client_cpf_or_cnpj UNIQUE (cpf_or_cnpj)
);

CREATE TABLE tb_technician (
                               id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name      VARCHAR(255) NOT NULL,
                               email     VARCHAR(255) NOT NULL,
                               specialty VARCHAR(255) NOT NULL,
                               CONSTRAINT uk_technician_email UNIQUE (email)
);

CREATE TABLE tb_order_service (
                                  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  title             VARCHAR(255) NOT NULL,
                                  description       TEXT NOT NULL,
                                  status            VARCHAR(255) NOT NULL,
                                  priority          VARCHAR(255) NOT NULL,
                                  created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                  finished_at       TIMESTAMP(6) WITH TIME ZONE,
                                  root_cause_report TEXT,
                                  client_id         BIGINT NOT NULL,
                                  technician_id     BIGINT,
                                  CONSTRAINT ck_order_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'FINISHED', 'CANCELED')),
                                  CONSTRAINT ck_order_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
                                  CONSTRAINT fk_order_client FOREIGN KEY (client_id) REFERENCES tb_client (id),
                                  CONSTRAINT fk_order_technician FOREIGN KEY (technician_id) REFERENCES tb_technician (id)
);

CREATE INDEX idx_order_client ON tb_order_service (client_id);
CREATE INDEX idx_order_technician ON tb_order_service (technician_id);
CREATE INDEX idx_order_created_at ON tb_order_service (created_at);