CREATE TABLE tb_user (
                         id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name          VARCHAR(255) NOT NULL,
                         email         VARCHAR(255) NOT NULL,
                         password_hash VARCHAR(255) NOT NULL,
                         role          VARCHAR(255) NOT NULL,
                         CONSTRAINT uk_user_email UNIQUE (email),
                         CONSTRAINT ck_user_role CHECK (role IN ('ADMIN', 'USER'))
);