CREATE TABLE tb_refresh_token (
                                  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  token_hash VARCHAR(255) NOT NULL,
                                  user_id    BIGINT NOT NULL,
                                  expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                  created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                  CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
                                  CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES tb_user (id)
);

CREATE INDEX idx_refresh_token_user ON tb_refresh_token (user_id);